format_version: 1
stack_name: python-base
resources_I_provision:
  docker_images:
    - dockerfile: ./Dockerfile
      repo: janus/python-base
      tags:
        - "2"
        - "2.0"
        - "2.0.0"
        - "python-3"
        - "python-3.6"
        - latest
